### ISSUE TITLE
Octyne future roadmap

### ISSUE THREAD

**Issue by retrixe** [retrixe/octyne#12]
**Octyne 1.x:**
- [ ] configurable crash limits

**Octyne 2.0 and later:**
- [ ] get rid of user-facing server designation? `(?<!internal)(?<!internal )server`
- [ ] remove JSON config support
- [ ] remove deprecated endpoints
- [ ] change the default port (42069 is... not great... what about 7877?)
- [ ] move all API endpoints to `/api`
