### ISSUE TITLE
Octyne 1.1.0 Roadmap

### ISSUE THREAD

**Issue by retrixe** [retrixe/octyne#6]
- [x] check if files are actually files everywhere
- [x] validate if path validation works on Windows
- [x] investigate PATCH file having a non-JSON body
